import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Layout from "../components/layout";
import { getSortedData, getCatData, getOwnerData, getContactData } from "../lib/data.js";
import Link from 'next/link';



// get static props
export async function getStaticProps() {
  const allData = await getSortedData();
  const allCats = await getCatData();
  const allOwners = await getOwnerData();
  const allContacts = await getContactData();
  return {
    props: { allData , allCats, allOwners, allContacts}
  };
}

// exports Home page component
export default function Home( { allData, allCats, allOwners, allContacts } ) {
  return (
    <>
      <Head>
        <title>Carinas Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      <h1>Carinas Cats</h1>

      <div className="list-group">
        <h4>Contacts:</h4>
        {allContacts && allContacts.map(
          ({id, name}) => (
            <p key={id}>
              {name}
            </p>
          )
        )
        }
      </div>

      </Layout>
    </>
  );
}
