import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Layout from "../components/layout";
import { getSortedData } from "../lib/data.js";
import Link from 'next/link';



// get static props
export async function getStaticProps() {
  const allCats = await getSortedData();
  return {
    props: { allCats }
  };
}

// exports Home page component
export default function Home( { allCats } ) {
  return (
    <>
      <Head>
        <title>Carinas Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout home>
      <h1>Hello from Carinas Cats</h1>
      <div className="list-group">
        {allCats && allCats.map(
          ({id, name}) => (
            <Link key={id} href={`/cats/${id}`} className="list-group-item">
              {name}
            </Link>
          )
        )
        }
      </div>
      </Layout>
    </>
  );
}
